### ISSUE TITLE
关于douyutv.com加密算法问题

### ISSUE THREAD

**Issue by iliul** [yan12125/douyu-hack#1]
看到you-get的斗鱼破解是你提供的加密算法，请问你是如何做到的呢？md5加密是不可逆的，你是如何分析出原始字符串的构建逻辑的呢，很感兴趣，因为我想写一个panda.tv的破解程序，但是我想了好久一直无法破解下面的字符串，

> http://pl3.live.panda.tv/live_panda/4b0904bbdb295b039405d8a7879ae43b.flv

期待回复！

**Comment by yan12125** [comment]
我是破解Android App，攔截MD5()函數的參數。

**Comment by iliul** [comment]
回复收到了，谢谢。
